
name: analyzer

on:
  - push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
       
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install
        run: make install
  
      - name: Run linter
        run: make lint

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: make test
    
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CC_TEST_REPORTER_ID}}
          file: ./build/logs/clover.xml
          fail_ci_if_error: true
